import type { ChangedFile } from '../src/types.js'
import { describe, expect, it } from 'vitest'
import { isLikelyAiGenerated } from '../src/heuristic.js'

describe('isLikelyAiGenerated', () => {
  it('flags PRs exceeding the line threshold', () => {
    const files: ChangedFile[] = [
      { filename: 'a.ts', additions: 600, deletions: 500 },
    ]
    const { likely } = isLikelyAiGenerated(files, 1000)
    expect(likely).toBe(true)
  })

  it('does not flag small PRs', () => {
    const files: ChangedFile[] = [
      { filename: 'a.ts', additions: 10, deletions: 5 },
    ]
    const { likely } = isLikelyAiGenerated(files, 1000)
    expect(likely).toBe(false)
  })

  it('reports total lines changed', () => {
    const files: ChangedFile[] = [
      { filename: 'a.ts', additions: 100, deletions: 50 },
      { filename: 'b.ts', additions: 200, deletions: 30 },
    ]
    const { totalLinesChanged } = isLikelyAiGenerated(files, 1000)
    expect(totalLinesChanged).toBe(380)
  })

  it('does not flag conventional commit messages as AI', () => {
    const files: ChangedFile[] = [
      { filename: 'a.ts', additions: 300, deletions: 300 },
    ]
    const { likely } = isLikelyAiGenerated(files, 1000, [
      'feat(auth): add login endpoint',
    ])
    expect(likely).toBe(false)
  })

  it('flags commit messages with explicit AI tool references', () => {
    const files: ChangedFile[] = [
      { filename: 'a.ts', additions: 300, deletions: 300 },
    ]
    const { likely } = isLikelyAiGenerated(files, 1000, [
      'Generated by Cursor',
    ])
    expect(likely).toBe(true)
  })

  it('flags commit messages with co-authored-by AI tools', () => {
    const files: ChangedFile[] = [
      { filename: 'a.ts', additions: 300, deletions: 300 },
    ]
    const { likely } = isLikelyAiGenerated(files, 1000, [
      'fix: resolve bug\n\nCo-authored-by: copilot[bot]',
    ])
    expect(likely).toBe(true)
  })

  it('does not flag [bot] appearing mid-word or mid-line', () => {
    const files: ChangedFile[] = [
      { filename: 'a.ts', additions: 300, deletions: 300 },
    ]
    const { likely } = isLikelyAiGenerated(files, 1000, [
      'fix array[bot] index handling',
    ])
    expect(likely).toBe(false)
  })
})
