import { describe, expect, it } from 'vitest'
import { parse } from '../src/parser.js'
import { evaluateAiHeuristic, evaluateProtectedChangeSet } from '../src/policy.js'

describe('evaluateAiHeuristic', () => {
  it('flags when total lines are above threshold', () => {
    const result = evaluateAiHeuristic([
      { filename: 'a.ts', additions: 600, deletions: 500 },
    ], 1000)

    expect(result.likelyAiGenerated).toBe(true)
    expect(result.totalLinesChanged).toBe(1100)
  })

  it('flags AI-like commit messages above half-threshold', () => {
    const result = evaluateAiHeuristic([
      { filename: 'a.ts', additions: 300, deletions: 260 },
    ], 1000, ['Generated by Cursor'])

    expect(result.likelyAiGenerated).toBe(true)
    expect(result.totalLinesChanged).toBe(560)
  })

  it('does not flag small human-like changes', () => {
    const result = evaluateAiHeuristic([
      { filename: 'a.ts', additions: 20, deletions: 5 },
    ], 1000, ['feat: improve parser'])

    expect(result.likelyAiGenerated).toBe(false)
  })
})

describe('evaluateProtectedChangeSet', () => {
  it('returns only non-free violations and includes heuristic summary', () => {
    const ruleSets = [parse('docs/\n!LICENSE')]

    const result = evaluateProtectedChangeSet({
      changedFiles: [
        { filename: 'docs/specs/guide.md', additions: 5, deletions: 1 },
        { filename: 'LICENSE', additions: 2, deletions: 0 },
        { filename: 'src/index.ts', additions: 10, deletions: 2 },
      ],
      ruleSets,
      aiThreshold: 1000,
      commitMessages: ['chore: update docs'],
    })

    expect(result.violations).toHaveLength(2)
    expect(result.violations.map(v => [v.filename, v.level])).toEqual([
      ['docs/specs/guide.md', 'confirm'],
      ['LICENSE', 'readonly'],
    ])
    expect(result.likelyAiGenerated).toBe(false)
    expect(result.totalLinesChanged).toBe(20)
  })
})
