import type { HumanRuleSet } from './types'
import { classify } from './classifier'

export interface ChangedFileStat {
  filename: string
  additions: number
  deletions: number
}

export interface ProtectedViolation extends ChangedFileStat {
  level: 'confirm' | 'readonly'
}

export interface AiHeuristicResult {
  likelyAiGenerated: boolean
  totalLinesChanged: number
}

export interface ProtectedPolicyEvaluation {
  violations: ProtectedViolation[]
  likelyAiGenerated: boolean
  totalLinesChanged: number
}

const AI_COMMIT_PATTERNS = [
  /generated by (copilot|cursor|codex|cline|windsurf|aider|claude)/i,
  /auto-generated/i,
  /\bai[- ]assisted\b/i,
  /co-authored-by:.*\b(copilot|cursor|codex|cline|windsurf|aider)\b/i,
  /\[bot\]$/im,
]

/**
 * Estimate whether a change set is likely AI-generated.
 *
 * Two-tier approach:
 * - flags immediately when total changed lines reach the threshold
 * - below the threshold, flags only when AI-like commit signals are
 *   present and changes exceed half the threshold (conservative path)
 */
export function evaluateAiHeuristic(
  changedFiles: ChangedFileStat[],
  threshold: number,
  commitMessages: string[] = [],
): AiHeuristicResult {
  const totalLinesChanged = changedFiles.reduce(
    (sum, file) => sum + file.additions + file.deletions,
    0,
  )

  if (totalLinesChanged >= threshold) {
    return {
      likelyAiGenerated: true,
      totalLinesChanged,
    }
  }

  const hasAiSignal = commitMessages.some(message =>
    AI_COMMIT_PATTERNS.some(pattern => pattern.test(message)),
  )

  return {
    likelyAiGenerated: hasAiSignal && totalLinesChanged > threshold / 2,
    totalLinesChanged,
  }
}

/**
 * Classify changed files and collect non-free violations.
 */
export function collectProtectedViolations(
  changedFiles: ChangedFileStat[],
  ruleSets: HumanRuleSet[],
): ProtectedViolation[] {
  const violations: ProtectedViolation[] = []

  for (const file of changedFiles) {
    const level = classify(file.filename, ruleSets)
    if (level === 'free')
      continue

    violations.push({
      filename: file.filename,
      additions: file.additions,
      deletions: file.deletions,
      level,
    })
  }

  return violations
}

/**
 * Evaluate both boundary violations and AI-likelihood in one pass.
 */
export function evaluateProtectedChangeSet(options: {
  changedFiles: ChangedFileStat[]
  ruleSets: HumanRuleSet[]
  aiThreshold: number
  commitMessages?: string[]
}): ProtectedPolicyEvaluation {
  const violations = collectProtectedViolations(options.changedFiles, options.ruleSets)
  const heuristic = evaluateAiHeuristic(
    options.changedFiles,
    options.aiThreshold,
    options.commitMessages ?? [],
  )

  return {
    violations,
    likelyAiGenerated: heuristic.likelyAiGenerated,
    totalLinesChanged: heuristic.totalLinesChanged,
  }
}
