blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/zhangyu94/humanfile#learn-more
    about: Check the documentation before opening an issue
  - name: Q&A and Open-Ended Discussion
    url: https://github.com/zhangyu94/humanfile/discussions
    about: Ask questions, share ideas, and start broader conversations
